### ISSUE TITLE
How to insert logo?

### ISSUE THREAD

**Issue by sciefylab** [2amigos/yii2-qrcode-helper#10]
Hi Man,
How to insert logo on our qrcode?

thanks,

**Comment by aekkapun** [comment]
How to ?. Please.

**Comment by tonydspaniard** [comment]
use same formula in here but with resulting image instead: https://gist.github.com/NTICompass/1283249

**Comment by tonydspaniard** [comment]
@sciefylab @aekkapun working on a new version of this library that will BC with previous versions. 

https://github.com/2amigos/yii2-qrcode-helper/blob/develop/tests/QrCodeTest.php#L75 

Will close this ticket as its not longer valid. Will publish the new version as soon as a write the documentation.
