### ISSUE TITLE
How to use on pdf

### ISSUE THREAD

**Issue by firdows** [2amigos/yii2-qrcode-helper#11]

**Comment by tonydspaniard** [comment]
You will have to use a library to add the  resulting image into your pdf document. Something like https://mozilla.github.io/pdf.js/

**Comment by DBX12** [comment]
I have the same issue. I'm using [Kartik-v's mpdf extension for Yii2](https://github.com/kartik-v/yii2-mpdf) and your QR-Code extension. The issue I run into is the following:
In my view `_pdf` I "include" the QR code by `<img src="<?= Url::to(['route/qrcode','text'=>$model->qr_code_content]) ?>" />`
In my Controller I have this function
```php
public function actionQrcode($text){
    Yii::$app->response->format = Response::FORMAT_RAW;
    Yii::$app->response->headers->set('Content-Type','image/png');
    return QrCode::png($text)
}
```

The Controller renders the view in the `actionPdf`

```php
public function actionPdf($id) {
        $model = $this->findModel($id);
        #return $this->renderPartial('_pdf', ['model' => $model]);
        $content = $this->renderPartial('_pdf', ['model' => $model]);
        $pdf = new Pdf([
            'content' => $content,
            'filename' => 'Ticket_' . $model->id . '.pdf',
            'options' => [
                'title' => 'Your ticket as '
            ],
            'cssFile' => '@webroot/css/pdf.css'
        ]);
        $pdf->render();
    }
```

In the PDF the QR code is displayed as "missing image" icon, if I uncomment the third line (`return $this->renderPartial(...` the page renders as normal HTML and the QR code is displayed correctly.
I will also open an issue for the mpdf extension.  Please look up the issue together with kartik-v, thx
