### ISSUE TITLE
Class 'doamigos\qrcode\formats\vCard' not found

### ISSUE THREAD

**Issue by vc7deo** [2amigos/yii2-qrcode-helper#12]
im getting following error

![image](https://cloud.githubusercontent.com/assets/8149102/16263431/f56a6092-3891-11e6-9e1b-9ff0ff29dacc.png)

**Comment by amigo-tabin** [comment]
@vc7deo you are missing an "s" in the Class path. It is "dosamigos" not "doamigos"

**Comment by vc7deo** [comment]
Thank you @amigo-tabin .

please adjust the documentation also

**Comment by vc7deo** [comment]
i added vcard like this 

  $vc = new vCard();
    $vc->name = "kannan";
    $vc->fullName = "kannan vc";
    return QrCode::png($vc->getText());

**Comment by tonydspaniard** [comment]
yes
