### ISSUE TITLE
read.md里的示例应该需要修改一下才能运行正常

### ISSUE THREAD

**Issue by lobtao** [2amigos/yii2-qrcode-helper#16]
`$response = \Yii::$app->response;
$response->headers->set('Content-Type', 'image/png');
$response->format = Response::FORMAT_RAW;
$mailTo = new MailTo([
        'email' => 'lobtao@qq.com',
        ]);
        return QrCode::png($mailTo->getText());`

**Comment by tonydspaniard** [comment]
English?
