### ISSUE TITLE
Is it possible to save this QR code as a file?

### ISSUE THREAD

**Issue by vostramedia** [2amigos/yii2-qrcode-helper#17]
Is it possible to save this qr code as a file into the database and file system? As the image has no source file it simply points to the function that generates it.

Controller:
```
public function actionQrCode() {
        return QrCode::png( Yii::$app->getRequest()->getQueryParam('id'),  'file.png', Enum::QR_ECLEVEL_L, 8, 4, true );
    }
```

HTML:
` <img src="<?= Url::to(['/product/qr-code', 'id' => $model->id])?>" />`

When I look at the source code for the image tag I see the following:
`<img src="/product/qr-code?id=17">`

How can I save this file?

**Comment by tonydspaniard** [comment]
you need to call that url= `/product/qr-code?id=?17` get its contents and save it into a file (i.e. `qr.png`)
