### ISSUE TITLE
[QUESTION] Event (iCalendar)

### ISSUE THREAD

**Issue by timmy78** [2amigos/yii2-qrcode-helper#3]
Hi

Can we use an [event/calendar qr code](https://github.com/zxing/zxing/wiki/Barcode-Contents#ical) ([iCalendar](http://en.wikipedia.org/wiki/ICalendar) / VCalendar) ?
Like here : http://qrickit.com/qrickit_apps/qrickit_qrcode_creator_vcal.php
or here : https://www.unitag.io/fr/qrcode

Thank you !

**Comment by tonydspaniard** [comment]
We should create a new format class only

**Comment by tonydspaniard** [comment]
Here is the spec:https://github.com/zxing/zxing/wiki/Barcode-Contents

**Comment by tonydspaniard** [comment]
added on https://github.com/2amigos/yii2-qrcode-helper/commit/c09a2377a2226867d163405d44d96b53d6533533
