### ISSUE TITLE
how to download qr image to local

### ISSUE THREAD

**Issue by mafeifan** [2amigos/yii2-qrcode-helper#8]
I use  \dosamigos\qrcode\QrCode::png($url);  to show qrcode. it's perfect.
when I run action '/user/qrcode' I get 
"�PNG  IHDRoo�#PLTE���U��~'IDAT8��Ա��0��(ܙ"y w^�e��J���I^�׹@��I��5��Q�!���!�ƫ���N�U:�&<�2� �2��R��S��՞��_�xT%{�����U�~����&#~���}�=lCF�:�5�%ɔX��(i���:�l&m��%�Ό��L�.ڤ��e&̥��%��w��T6I�\�ґ��r$��T�F���H�]�^_�ɳ�6M�[����$[t���=@:ﻥ̖�&v쒸�XP�8sD�,����G����79ڭ��S\R���z�� ?(�!�ʣ�JC*�e��w������X5IEND�B`�"
I want to add one button, when I click the button I can download the qrcode image to local

**Comment by mafeifan** [comment]
public function actionQrcode(){
        $consumer = \Yii::$app->user->identity->consumer;
        $url = $consumer->getPromoterCodeUrl(true);
        return \dosamigos\qrcode\QrCode::png($url);
    }

    public function actionQrdown(){
        $this->actionQrcode();
        $file_name = 'qrcode.png';
        $mime = 'application/force-download';
        header('Pragma: public'); // required
        header('Expires: 0'); // no cache
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Cache-Control: private',false);
        header('Content-Type: '.$mime);
        header('Content-Disposition: attachment; filename="'.basename($file_name).'"');
        header('Content-Transfer-Encoding: binary');
        header('Connection: close');
        //readfile($image); // push it out
        exit();
    }


I use above code, have a better way?

**Comment by tonydspaniard** [comment]
i think is pretty good the way you do
