### ISSUE TITLE
Console application

### ISSUE THREAD

**Issue by galkindev** [2amigos/yii2-qrcode-helper#9]
Hello, your qr-code helper doesn’t work in a console application (Yii2 Advanced Project Template). A console application doesn’t use a session component, but you are using this component in Tools::markTime($markerId) and in Tools::timeBenchmark().

Do you have any idea to fix this issue?

**Comment by y284663247** [comment]
i have the some question, not work in a console application

**Comment by tonydspaniard** [comment]
best way would be to remove that...

**Comment by jafaripur** [comment]
@tonydspaniard when this issue will be fixed!

**Comment by tonydspaniard** [comment]
@jafaripur you are welcome for a PR

**Comment by tonydspaniard** [comment]
Fixed on #13
